version: '2'
services:
    db:
        container_name: example_db
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ../mysql:/var/lib/mysql
            - ../dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
    php:
        depends_on:
            - db
        container_name: example_php
        build:
            context: ../images/php7_normal_xdebug
            args:
                - "--name=php7_normal_xdebug"
        image: php7_normal_xdebug
        working_dir: /var/www
        volumes:
            - ../html:/var/www
        expose:
            - 9000
        environment:
            PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
            XDEBUG_CONFIG: remote_host=172.17.0.1 
            PHP_IDE_CONFIG: "serverName=docker"
        ports:
            - "2222:22" # ssh
            - "35729:35729" # live reload
        links:
            - db
        extra_hosts:
            - "example:172.17.0.1"
    web:
        depends_on:
            - php
        container_name: example_web
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ../html:/var/www
            - ../site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php