version: '2'
services:
    web:
        container_name: example_web
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ../html:/var/www
            - ../site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: example_php
        #image: php7_normal
        build: 
            context: ../images/php7_normal
            args:
                - "--name=php7_normal"
        working_dir: /var/www
        volumes:
            - ../html:/var/www
        links:
            - db
    db:
        container_name: example_db
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ../mysql:/var/lib/mysql
            - ../dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
